# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Erica Garaffo's Site
email: erica.garaffo@sanjoseca.gov
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my site! Erica Garaffo loves data, smart cities, 
  civic innovation, and learning new computer skills!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ericagaraffo.com" # the base hostname & protocol for your site
twitter_username: erica_garaffo
github_username:  ericagaraffo

# Build settings
#markdown: kramdown
